"""Source-confidence eligibility, cost, stipend, and acceptance data.

Applied onto extra_opportunities in app.py. Does not change scoring logic.
last_verified: 2026-08-19
"""

TRANSPARENCY_DEFAULTS = {
    "eligibility_summary": "Check official eligibility",
    "eligible_grades": "",
    "age_requirements": "Not stated",
    "nyc_residency_required": "Not stated",
    "nyc_school_required": "Not stated",
    "borough_restrictions": "None stated",
    "citizenship_requirement": "Not stated",
    "income_requirement": "Not stated",
    "underrepresented_preference": "Not stated",
    "required_coursework": "Not stated",
    "gpa_requirement": "Not stated",
    "prior_program_requirement": "Not stated",
    "school_nomination_required": "No",
    "other_restrictions": "",
    "cost_category": "Unknown / check official site",
    "tuition_cost": "",
    "financial_aid_status": "Unknown / check official site",
    "scholarship_availability": "No aid stated",
    "stipend_status": "Unknown",
    "stipend_amount": "",
    "stipend_display": "Check official site",
    "acceptance_rate_confidence": "Not available",
    "acceptance_rate_source": "Not publicly reported",
    "last_verified": "2026-08-19",
}

# Card-facing source labels derived from acceptance_rate_confidence.
CONFIDENCE_SOURCE_LABEL = {
    "Official": "Official",
    "Calculated": "Calculated from official data",
    "Estimated — High confidence": "Unofficial estimate",
    "Estimated — Moderate confidence": "Unofficial estimate",
    "Estimated — Low confidence": "Unofficial estimate",
    "Not available": "",
}


def _free_funded():
    return {
        "cost": "Free",
        "cost_category": "Free",
        "tuition_cost": "None — program is free",
        "financial_aid": "Not needed — fully funded",
        "financial_aid_status": "Not needed — fully funded",
        "scholarship_availability": "Not needed — program is fully funded",
    }


def _not_reported():
    return {
        "acceptance_rate": "Not publicly reported",
        "acceptance_rate_confidence": "Not available",
        "acceptance_rate_source": "Not publicly reported",
    }


TRANSPARENCY_UPDATES = {
    "Research Science Institute (RSI) at MIT": {
        **_free_funded(),
        "eligibility_summary": "Current 11th graders (rising seniors) • No NYC residency requirement",
        "eligible_grades": "11",
        "age_requirements": "No simple age cutoff published — current 11th graders only",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "International students may apply through CEE/country processes; U.S. applicants apply through CEE",
        "income_requirement": "Not stated",
        "required_coursework": "Strong STEM coursework expected; no single published course list",
        "gpa_requirement": "Not stated as a numeric cutoff",
        "school_nomination_required": "No",
        "other_restrictions": "High school seniors are not eligible. Current juniors only.",
        "stipend_status": "Not paid",
        "stipend_amount": "",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Free Program",
        "acceptance_rate": "Not publicly reported",
        "acceptance_rate_confidence": "Not available",
        "acceptance_rate_source": "CEE publishes a cohort of about 100 students but does not currently publish an official acceptance rate or current-year applicant count.",
        "requirements": "Current 11th grader (rising senior); application, recommendations, and transcript; seniors are not eligible",
    },
    "Carnegie Mellon SAMS": {
        **_free_funded(),
        "eligibility_summary": "Current 11th graders • U.S. citizen or permanent resident • Age 16+",
        "eligible_grades": "11",
        "age_requirements": "16+ by program start",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or permanent resident",
        "income_requirement": "Not stated as a hard cutoff",
        "underrepresented_preference": "Program emphasizes students historically underrepresented in STEM",
        "school_nomination_required": "No",
        "other_restrictions": "Students typically cover travel to Pittsburgh",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Free Program",
        **_not_reported(),
        "acceptance_rate_source": "Carnegie Mellon does not publish an official SAMS acceptance rate.",
        "requirements": "Current 11th grader; age 16+ by start; U.S. citizen or permanent resident",
    },
    "Columbia Engineering the Next Generation (ENG)": {
        **_free_funded(),
        "eligibility_summary": "NYC students • Rising seniors • Work authorization required",
        "eligible_grades": "11",
        "age_requirements": "Must meet NYC work-eligibility requirements",
        "nyc_residency_required": "Yes — NYC students",
        "nyc_school_required": "Yes",
        "citizenship_requirement": "Must be legally allowed to work in NYC",
        "underrepresented_preference": "Bronx and NYC public-school students are a core audience",
        "prior_program_requirement": "FoR track requires prior work or volunteer experience",
        "school_nomination_required": "No",
        "stipend_status": "Paid",
        "stipend_amount": "$17/hour (FoR track, 25 hours/week)",
        "stipend_display": "$17/hour stipend (FoR track)",
        "paid_status": "Paid — 2026 FoR stipend listed at $17/hour, 25 hours/week",
        **_not_reported(),
        "acceptance_rate_source": "Columbia ENG does not publish an official acceptance rate.",
        "requirements": "Current 11th grader/rising NYC senior; NYC school; legally allowed to work in NYC; FoR requires prior work or volunteer experience",
    },
    "Rockefeller University Jumpstart + SSRP": {
        **_free_funded(),
        "eligibility_summary": "NYC high school juniors and seniors • Age 16+",
        "eligible_grades": "11;12",
        "age_requirements": "16+ by program start",
        "nyc_residency_required": "Yes — NYC high school students",
        "nyc_school_required": "Yes",
        "citizenship_requirement": "Not stated as a separate published cutoff beyond school eligibility",
        "school_nomination_required": "No",
        "other_restrictions": "Full spring and summer commitment; selected applicants interview. Jumpstart supports 16 students.",
        "stipend_status": "Paid",
        "stipend_amount": "$3,750 total ($500 spring + $3,250 summer)",
        "stipend_display": "$3,750 stipend ($500 spring + $3,250 summer)",
        "paid_status": "Paid — official Jumpstart FAQ lists $500 spring and $3,250 summer",
        **_not_reported(),
        "acceptance_rate_source": "Rockefeller publishes a Jumpstart cohort of 16 students but does not publish applicant counts or an official acceptance rate.",
        "requirements": "NYC high school junior or senior; age 16+ at start; full spring/summer commitment; selected applicants interview",
    },
    "Columbia University Science Honors Program (SHP)": {
        "cost": "$900/year for new students beginning Fall 2026",
        "cost_category": "Tuition required",
        "tuition_cost": "$900/year for incoming students; $700/year for returning students (Fall 2026)",
        "financial_aid": "Available",
        "financial_aid_status": "Need-based program fee waivers available for documented financial hardship",
        "scholarship_availability": "Fee waivers may be granted after admission; applications considered regardless of need",
        "eligibility_summary": "Grades 10–12 • Live within 75 miles of Columbia",
        "eligible_grades": "10;11;12",
        "age_requirements": "Grade-based — apply while in grades 9–11 for the following year",
        "nyc_residency_required": "No — NY/NJ/CT students within 75 miles",
        "nyc_school_required": "No",
        "citizenship_requirement": "Not stated",
        "income_requirement": "Not required; hardship waivers available",
        "required_coursework": "Background in algebra, geometry, trigonometry, and probability plus elementary science",
        "school_nomination_required": "No — teacher recommendation required",
        "other_restrictions": "In-person Saturdays; students provide their own transportation. Entrance exam required.",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid",
        **_not_reported(),
        "acceptance_rate_source": "Columbia SHP does not publish an official acceptance rate.",
        "requirements": "Apply in grades 9–11 for the following year; live within 75 miles of campus; application, essay, transcript, recommendation, entrance exam; $50 application fee with hardship waiver option",
    },
    "AMNH Science Research Mentoring Program (SRMP)": {
        **_free_funded(),
        "eligibility_summary": "NYC students • Current 10th or 11th graders • Prior AMNH/partner pathway required",
        "eligible_grades": "10;11",
        "age_requirements": "Current 10th or 11th graders",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes",
        "prior_program_requirement": "Must meet AMNH prior-program or partner-school/program eligibility",
        "school_nomination_required": "Partner-program eligibility required",
        "stipend_status": "Paid",
        "stipend_amount": "$2,500",
        "stipend_display": "$2,500 stipend",
        "paid_status": "$2,500 stipend upon completion of research and program requirements",
        **_not_reported(),
        "acceptance_rate_source": "AMNH does not publish an official SRMP acceptance rate.",
        "requirements": "NYC student in current grade 10 or 11; passing classes; must meet AMNH prior-program or partner-school/program eligibility",
    },
    "New York Academy of Sciences Junior Academy": {
        **_free_funded(),
        "eligibility_summary": "Ages 13–17 • Open globally (virtual)",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "13–17 during the program",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "Open internationally",
        "school_nomination_required": "No",
        "other_restrictions": "Comfortable communicating in English; parental/guardian consent; ~3–4 hours per week",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Free Program",
        **_not_reported(),
        "acceptance_rate_source": "NYAS states it receives thousands of applications worldwide but does not publish an official acceptance rate.",
        "requirements": "Age 13–17 during the program; strong STEM interest; comfortable reading, writing, and communicating in English; parental/guardian consent; ability to work on an international team",
    },
    "MITES Summer": {
        **_free_funded(),
        "eligibility_summary": "Current 11th graders (rising seniors) • U.S. citizen or permanent resident",
        "eligible_grades": "11",
        "age_requirements": "No simple published age cutoff — rising seniors",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or permanent resident",
        "underrepresented_preference": "Program is designed to broaden access to MIT for students from underrepresented and underserved backgrounds",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Unpaid / Free Program",
        **_not_reported(),
        "acceptance_rate_source": "MIT does not publish an official MITES Summer acceptance rate.",
        "requirements": "Current 11th grader / rising senior; U.S. citizen or permanent resident; application, recommendations, and academic information",
    },
    "Columbia Engineering SHAPE": {
        "cost": "Tuition-based",
        "cost_category": "Tuition required",
        "tuition_cost": "About $6,241 total program cost (2026)",
        "financial_aid": "Available",
        "financial_aid_status": "Need-based full scholarships available for domestic students",
        "scholarship_availability": "Limited full-cost need-based scholarships; NYC school Districts 5 and 6 prioritized",
        "eligibility_summary": "Rising sophomores through recent graduates • Open beyond NYC",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "Typically 14–18; rising sophomores, juniors, seniors, and recent graduates",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "Financial aid is only available to domestic students and families",
        "income_requirement": "Aid is need-based for domestic students",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid",
        **_not_reported(),
        "acceptance_rate_source": "Columbia SHAPE does not publish an official acceptance rate.",
        "requirements": "Rising sophomore through recent high school graduate; application, essays, transcript/report card, recommendation, resume",
    },
    "NASA GISS / CCRI High School Research": {
        **_free_funded(),
        "eligibility_summary": "High school students • Project-specific eligibility",
        "eligible_grades": "10;11;12",
        "age_requirements": "Varies by project — check official eligibility",
        "nyc_residency_required": "Not required for all projects; NYC-area placements exist",
        "nyc_school_required": "No",
        "citizenship_requirement": "Some opportunities require U.S. citizenship",
        "gpa_requirement": "Some opportunities list GPA eligibility",
        "school_nomination_required": "No",
        "stipend_status": "Unknown",
        "stipend_display": "Varies by project — check official site",
        "paid_status": "Varies by project",
        **_not_reported(),
        "acceptance_rate_source": "NASA GISS / CCRI does not publish a single official high school acceptance rate.",
        "requirements": "Project-specific; some opportunities require U.S. citizenship and GPA eligibility",
    },
    "NASA Glenn High School Engineering Institute": {
        **_free_funded(),
        "eligibility_summary": "Upcoming juniors and seniors • Age 16+ • U.S. citizen or LPR",
        "eligible_grades": "11;12",
        "age_requirements": "16+ by program start",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or lawful permanent resident",
        "gpa_requirement": "GPA threshold listed on official materials — confirm current cycle",
        "school_nomination_required": "No — recommendation required",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid",
        **_not_reported(),
        "acceptance_rate_source": "NASA Glenn does not publish an official High School Engineering Institute acceptance rate.",
        "requirements": "Upcoming junior or senior; age requirement; GPA threshold; recommendation; U.S. citizenship or LPR",
    },
    "Learn & Earn": {
        **_free_funded(),
        "eligibility_summary": "NYC students • Ages 16–21 • Income/eligibility rules apply",
        "eligible_grades": "11;12",
        "age_requirements": "16–21",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes",
        "citizenship_requirement": "Must meet NYC work-eligibility rules",
        "income_requirement": "Income/eligibility requirements apply",
        "school_nomination_required": "No",
        "stipend_status": "Paid",
        "stipend_amount": "",
        "stipend_display": "Paid internship — amount not published",
        "paid_status": "Paid internship component",
        **_not_reported(),
        "acceptance_rate_source": "DYCD does not publish an official Learn & Earn acceptance rate; placement is eligibility-based.",
        "requirements": "NYC junior/senior; age 16–21; income and work-eligibility requirements apply",
    },
    "Work, Learn & Grow": {
        **_free_funded(),
        "eligibility_summary": "NYC youth • Ages 16–21 • Prior-program eligibility can apply",
        "eligible_grades": "10;11;12",
        "age_requirements": "16–21",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Often required — confirm current cycle",
        "income_requirement": "Program-specific eligibility can apply",
        "prior_program_requirement": "Prior-program eligibility can apply",
        "school_nomination_required": "No",
        "stipend_status": "Paid",
        "stipend_display": "Paid — amount not published",
        "paid_status": "Paid",
        **_not_reported(),
        "acceptance_rate_source": "DYCD does not publish an official Work, Learn & Grow acceptance rate.",
        "requirements": "NYC youth; age, school, and prior-program eligibility can apply",
    },
    "NYC Summer Youth Employment Program (SYEP)": {
        **_free_funded(),
        "eligibility_summary": "NYC residents • Ages 14–24 • Legally authorized to work",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "14–24",
        "nyc_residency_required": "Yes — must live in one of the five boroughs",
        "nyc_school_required": "No for community-based SYEP; some school-based options require NYC DOE enrollment",
        "citizenship_requirement": "Must be legally allowed to work in the United States / NYC",
        "school_nomination_required": "No",
        "other_restrictions": "Community-based SYEP uses a randomized lottery. Additional requirements apply to Ladders for Leaders.",
        "stipend_status": "Paid",
        "stipend_amount": "New York State minimum wage",
        "stipend_display": "Paid — NYS minimum wage",
        "paid_status": "Paid",
        **_not_reported(),
        "acceptance_rate_source": "DYCD does not publish a single official SYEP acceptance rate; community-based placement is lottery-based.",
        "requirements": "Permanent NYC resident; age 14–24; legally allowed to work; required identity and eligibility documents",
    },
    "STEM Matters NYC": {
        **_free_funded(),
        "eligibility_summary": "NYC public school students • Eligibility varies by program",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "Varies by individual STEM Matters offering",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid",
        **_not_reported(),
        "acceptance_rate_source": "NYC Public Schools does not publish a single official STEM Matters acceptance rate; offerings vary.",
        "requirements": "NYC student; eligibility varies by individual program",
    },
    "NYU Tandon ARISE": {
        **_free_funded(),
        "eligibility_summary": "NYC students • Rising juniors/seniors",
        "eligible_grades": "10;11",
        "age_requirements": "Rising juniors and seniors (current 10th or 11th graders at application)",
        "nyc_residency_required": "Yes — full-time NYC residents only",
        "nyc_school_required": "Yes — must attend NYC schools",
        "borough_restrictions": "None — all five boroughs",
        "citizenship_requirement": "Not stated as a separate published cutoff beyond NYC residency/school enrollment",
        "income_requirement": "Not stated as a hard cutoff",
        "underrepresented_preference": "Program strongly encourages students from historically excluded groups in STEM",
        "required_coursework": "At least one year of high school science and one year of high school math commonly required",
        "gpa_requirement": "Not stated as a numeric cutoff",
        "prior_program_requirement": "Not required",
        "school_nomination_required": "No",
        "other_restrictions": "Full 10-week commitment. Free Pinkerton-funded program. About 75 students participated in Summer 2026.",
        "stipend_status": "Paid",
        "stipend_amount": "$2,000",
        "stipend_display": "$2,000 stipend",
        "paid_status": "Paid — official NYU page lists a $2,000 stipend upon successful completion",
        "acceptance_rate": "~4–8% estimated",
        "acceptance_rate_confidence": "Estimated — Moderate confidence",
        "acceptance_rate_source": "Unofficial estimate based on reported cohort size and multiple secondary sources; NYU does not publish an official acceptance rate.",
        "requirements": "Full-time NYC resident attending an NYC school; rising junior or senior; full 10-week commitment; typically at least one year of high school science and math",
    },
    "Simons Summer Research Program": {
        "cost": "Free",
        "cost_category": "Free",
        "tuition_cost": "No tuition; residential housing/dining estimated at about $2,450 for summer 2026 if living on campus",
        "financial_aid": "Not needed — fully funded",
        "financial_aid_status": "Not needed — fully funded (tuition). Housing/dining billed separately for residential students.",
        "scholarship_availability": "Not needed for tuition — program is fully funded",
        "eligibility_summary": "Current 11th graders • U.S. citizen or permanent resident • School nomination required",
        "eligible_grades": "11",
        "age_requirements": "16+ by program start (no exceptions)",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or permanent resident",
        "school_nomination_required": "Yes — school nomination required; typically maximum of 2 nominees per school",
        "other_restrictions": "Students apply in 11th grade and participate the summer before senior year.",
        "stipend_status": "Paid",
        "stipend_amount": "",
        "stipend_display": "Stipend provided — amount not published",
        "paid_status": "Paid — stipend awarded at closing poster symposium; amount not published",
        "acceptance_rate": "about <5%",
        "acceptance_rate_confidence": "Official",
        "acceptance_rate_source": "Stony Brook Simons application guidelines: “Percentage of students admitted: about <5%”.",
        "requirements": "Current 11th grader; U.S. citizen or permanent resident; age 16+ by program start; school nomination required",
    },
    "MSK HOPP Summer Student Program": {
        **_free_funded(),
        "eligibility_summary": "Current juniors • Live within 25 miles of MSK (NY/NJ/CT) • 3.5 science GPA",
        "eligible_grades": "11",
        "age_requirements": "14+ by program start (2026 materials specified 14+ by June 2026)",
        "nyc_residency_required": "No — NY/NJ/CT within 25 miles of MSK Manhattan campus",
        "nyc_school_required": "No",
        "citizenship_requirement": "Must be legally authorized to work in the U.S.",
        "gpa_requirement": "3.5 science GPA",
        "school_nomination_required": "No",
        "other_restrictions": "Full eight-week commitment. HOPP reports sponsoring over 20 students annually.",
        "stipend_status": "Paid",
        "stipend_amount": "$1,200",
        "stipend_display": "$1,200 stipend",
        "paid_status": "Paid — 2026 stipend was $1,200",
        **_not_reported(),
        "acceptance_rate_source": "MSK reports sponsoring over 20 HOPP summer students annually but does not publish applicant counts or an official acceptance rate.",
        "requirements": "Current high school junior; live in NY/NJ/CT within 25 miles of MSK main campus; legally authorized to work in U.S.; 3.5 science GPA; full eight-week commitment",
    },
    "Columbia BRAINYAC": {
        **_free_funded(),
        "eligibility_summary": "NYC students • Grades 10–11 • Eligible partner program/school required",
        "eligible_grades": "10;11",
        "age_requirements": "Grade-based eligibility",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes — through an eligible partner program/school",
        "prior_program_requirement": "Must be enrolled in an eligible partner program/school such as S-PREP, BioBus, Lang Youth Medical, Columbia Secondary School, or Double Discovery Center",
        "school_nomination_required": "Partner-program pathway required",
        "stipend_status": "Paid",
        "stipend_amount": "",
        "stipend_display": "Stipend provided — amount not published",
        "paid_status": "Paid stipend — amount not publicly listed on current program page",
        **_not_reported(),
        "acceptance_rate_source": "Columbia BRAINYAC does not publish an official acceptance rate.",
        "requirements": "NYC resident in grade 10 or 11 and enrolled in an eligible partner program/school such as S-PREP, BioBus, Lang Youth Medical, Columbia Secondary School, or Double Discovery Center",
    },
    "MSK Bridge to Biostats Summer Program": {
        **_free_funded(),
        "eligibility_summary": "NYC students • Rising sophomores through seniors",
        "eligible_grades": "9;10;11",
        "age_requirements": "Rising sophomore through rising senior",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes",
        "required_coursework": "Interest in math, computing, or data science; recommendation and transcript required",
        "school_nomination_required": "No",
        "stipend_status": "Paid",
        "stipend_amount": "",
        "stipend_display": "Stipend provided — amount not published",
        "paid_status": "Paid — current program page confirms paid participation; amount not publicly listed",
        **_not_reported(),
        "acceptance_rate_source": "MSK does not publish an official Bridge to Biostats acceptance rate.",
        "requirements": "NYC resident attending school in NYC; rising sophomore through rising senior; interest in math/computing/data science; recommendation and transcript",
    },
    "Columbia YES in THE HEIGHTS": {
        **_free_funded(),
        "eligibility_summary": "High school students • Verify current neighborhood/grade eligibility",
        "eligible_grades": "10;11;12",
        "age_requirements": "High school students — check current cycle requirements",
        "nyc_residency_required": "Typically yes — confirm current neighborhood eligibility",
        "nyc_school_required": "Confirm current cycle",
        "school_nomination_required": "No",
        "stipend_status": "Unknown",
        "stipend_display": "Not publicly stated — check official site",
        "paid_status": "Check official 2027 cycle details",
        **_not_reported(),
        "acceptance_rate_source": "Columbia YES in THE HEIGHTS does not publish an official acceptance rate.",
        "requirements": "Application materials include cover letter, resume, and full summer commitment; verify grade and neighborhood eligibility for current cycle",
    },
    "Columbia Secondary School Field Research Program (SSFRP)": {
        **_free_funded(),
        "eligibility_summary": "Current high school students • Age 16+ • Able to commute to Lamont",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "16+ by internship start",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "school_nomination_required": "No",
        "other_restrictions": "Must be able to commute to Lamont-Doherty Earth Observatory in Palisades, NY; full six-week commitment",
        "stipend_status": "Unknown",
        "stipend_display": "Not publicly stated — check official site",
        "paid_status": "Check official 2027 cycle details",
        **_not_reported(),
        "acceptance_rate_source": "Columbia SSFRP does not publish an official acceptance rate.",
        "requirements": "Currently enrolled high school student; age 16+ by start; able to commute; full six-week commitment",
    },
    "Columbia BrainSTORM Mentorship Program": {
        **_free_funded(),
        "eligibility_summary": "High school students in grades 9–12 • Open nationwide",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "High school students nationwide",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not publicly listed as a paid program",
        **_not_reported(),
        "acceptance_rate_source": "Columbia BrainSTORM does not publish an official acceptance rate.",
        "requirements": "High school student in grades 9–12; application includes research interests, personal statement, and resume/CV",
    },
    "MSK Science Enrichment Program (SEP)": {
        **_free_funded(),
        "eligibility_summary": "High school juniors • Partner-school nomination required • Biology completed",
        "eligible_grades": "11",
        "age_requirements": "High school juniors",
        "nyc_residency_required": "Typically NYC partner-school students",
        "nyc_school_required": "Yes — MSK SEP partner school",
        "required_coursework": "Completed a full year of biology",
        "school_nomination_required": "Yes — nominated by an MSK SEP partner school",
        "stipend_status": "Paid",
        "stipend_amount": "$4,200",
        "stipend_display": "$4,200 stipend",
        "paid_status": "Paid — current program page lists a total $4,200 stipend",
        **_not_reported(),
        "acceptance_rate_source": "MSK does not publish an official SEP acceptance rate.",
        "requirements": "High school junior; completed a full year of biology; must be nominated by an MSK SEP partner school",
    },
    "Rockefeller Summer Neuroscience Program (SNP)": {
        **_free_funded(),
        "eligibility_summary": "NYC public high school students • Age 16+",
        "eligible_grades": "10;11;12",
        "age_requirements": "16+ by program start",
        "nyc_residency_required": "Yes — NYC public high school students",
        "nyc_school_required": "Yes — NYC public high school",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Free Program",
        **_not_reported(),
        "acceptance_rate_source": "Rockefeller SNP does not publish an official acceptance rate.",
        "requirements": "Must attend an NYC public high school and be at least 16 years old by program start",
    },
    "CUNY STEM Research Academy": {
        **_free_funded(),
        "eligibility_summary": "NYC public high school students • Campus-specific GPA/Regents rules",
        "eligible_grades": "10;11",
        "age_requirements": "Grade-based eligibility varies by CUNY campus",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes — NYC public high school",
        "gpa_requirement": "Varies by campus; may include GPA and Regents scores",
        "school_nomination_required": "No",
        "stipend_status": "Unknown",
        "stipend_display": "Check campus — amount not consistently published",
        "paid_status": "Check individual CUNY campus for current stipend details",
        **_not_reported(),
        "acceptance_rate_source": "CUNY does not publish a systemwide official acceptance rate. Campus cohort sizes (for example CCNY selecting 25 students for Spring 2026) are not the same as an acceptance rate.",
        "requirements": "NYC public high school student; requirements vary by campus and may include GPA, Regents scores, transcript, and writing sample",
    },
    "BioBus High School Junior Scientist Internship": {
        **_free_funded(),
        "eligibility_summary": "NYC high school students • Location-specific placements",
        "eligible_grades": "9;10;11;12",
        "age_requirements": "High school students — program-specific eligibility applies",
        "nyc_residency_required": "Yes",
        "nyc_school_required": "Yes",
        "school_nomination_required": "No",
        "stipend_status": "Paid",
        "stipend_amount": "",
        "stipend_display": "Paid hourly — amount not published",
        "paid_status": "Paid hourly internship",
        **_not_reported(),
        "acceptance_rate_source": "BioBus reported a record number of 2026–27 applications but does not publish an official acceptance rate.",
        "requirements": "NYC high school student; specific location/program eligibility applies",
    },
    "Princeton AI4ALL": {
        **_free_funded(),
        "eligibility_summary": "Rising 11th graders • Low-income criteria • U.S. or Puerto Rico",
        "eligible_grades": "10",
        "age_requirements": "Rising 11th graders",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "Must live and attend high school in the U.S. or Puerto Rico",
        "income_requirement": "Must meet Princeton AI4ALL low-income criteria",
        "underrepresented_preference": "Low-income students; program aims to broaden participation in AI",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Free Program",
        **_not_reported(),
        "acceptance_rate_source": "Princeton AI4ALL does not publish an official acceptance rate.",
        "requirements": "Rising 11th grader living and attending high school in U.S. or Puerto Rico; must meet Princeton AI4ALL low-income criteria",
    },
    "NASA GeneLab for High Schools (GL4HS)": {
        **_free_funded(),
        "eligibility_summary": "Rising juniors/seniors • U.S. citizen or permanent resident • 3.0+ GPA",
        "eligible_grades": "10;11;12",
        "age_requirements": "Rising juniors, rising seniors, and eligible incoming college freshmen",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or permanent resident attending a U.S. high school",
        "required_coursework": "At least one high school biology course",
        "gpa_requirement": "3.0+ unweighted GPA",
        "school_nomination_required": "No",
        "other_restrictions": "Reliable computer and internet required (virtual program)",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Free Program",
        **_not_reported(),
        "acceptance_rate_source": "NASA GeneLab for High Schools does not publish an official acceptance rate.",
        "requirements": "U.S. citizen or permanent resident attending a U.S. high school; rising junior/senior; 3.0+ unweighted GPA; at least one high school biology course; reliable computer/internet",
    },
    "NASA STEM Enhancement in Earth Science (SEES) High School Summer Intern": {
        "cost": "Varies — scholarships and a $2,000 tuition option",
        "cost_category": "Varies — scholarships or $2,000 tuition",
        "tuition_cost": "Virtual: no cost. Scholarship on-site: tuition/housing/meals covered. Paid on-site option: $2,000 tuition including meals, housing, tours, and local travel.",
        "financial_aid": "Available",
        "financial_aid_status": "Full scholarships available (tuition, housing, meals); travel scholarships available; virtual participation is free",
        "scholarship_availability": "Full scholarships available; travel scholarships available and do not affect selection",
        "eligibility_summary": "Current sophomores and juniors • U.S. citizens only • Age 16+",
        "eligible_grades": "10;11",
        "age_requirements": "16 by July 5, 2026 (no exceptions for that cycle)",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizens only",
        "income_requirement": "Need is considered; students with limited STEM access are encouraged to apply",
        "underrepresented_preference": "Students with limited STEM access are encouraged to apply",
        "prior_program_requirement": "Previous SEES interns are not eligible to repeat as interns",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / scholarship or tuition-based internship",
        "acceptance_rate": "~11%",
        "acceptance_rate_confidence": "Calculated",
        "acceptance_rate_source": "Calculated from official SEES FAQ figures: about 215 accepted of ~2,000 applicants in 2024 (215 / 2,000 × 100 ≈ 10.8%).",
        "requirements": "U.S. citizen; current high school sophomore or junior (rising junior/senior); at least 16 by the on-site start date; cannot have been a SEES intern previously",
    },
    "Boston University RISE Internship": {
        "cost": "Tuition required",
        "cost_category": "Tuition required",
        "tuition_cost": "2026: $5,930 tuition + $485 service fees; $75 application fee; residential room and board extra (about $3,978–$4,320)",
        "financial_aid": "Available",
        "financial_aid_status": "Limited need-based financial aid available",
        "scholarship_availability": "Limited need-based aid; not a full-scholarship program for all students",
        "eligibility_summary": "Rising seniors • U.S. citizen or permanent resident",
        "eligible_grades": "11",
        "age_requirements": "Entering senior year of high school",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or legal permanent resident",
        "income_requirement": "Aid is need-based and limited",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Tuition-based Program",
        **_not_reported(),
        "acceptance_rate_source": "BU states RISE places up to about 100 students in STEM labs but does not publish an official acceptance rate or applicant count.",
        "requirements": "Current high school junior entering senior year; U.S. citizen or permanent resident; application, transcript, essay, and recommendation",
    },
    "George Mason Aspiring Scientists Summer Internship Program (ASSIP)": {
        "cost": "Tuition required",
        "cost_category": "Tuition required",
        "tuition_cost": "$1,299 tuition for 3 college credits (2025–2026 undergraduate tuition basis)",
        "financial_aid": "No aid stated",
        "financial_aid_status": "No aid stated on the official tuition page — confirm with the program",
        "scholarship_availability": "No aid stated",
        "eligibility_summary": "Age 15+ (16+ for wet lab) • High school and undergraduate",
        "eligible_grades": "10;11;12",
        "age_requirements": "15+ overall; 16+ typically required for in-person wet-lab placements",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "Not stated as a published cutoff on the main program page",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Tuition-based Program",
        **_not_reported(),
        "acceptance_rate_source": "George Mason ASSIP does not publish an official acceptance rate.",
        "requirements": "Students age 15+ (16+ for many wet-lab placements); application and mentor matching; exact eligibility varies by research placement",
    },
    "Stanford Institutes of Medicine Summer Research Program (SIMR)": {
        **_free_funded(),
        "financial_aid_status": "Not needed — fully funded. Limited need-based stipends for some students; $50 application fee with waivers if family income is under $80,000 or for special circumstances.",
        "eligibility_summary": "Current juniors and seniors • U.S. citizen or permanent resident • Age 16+",
        "eligible_grades": "11;12",
        "age_requirements": "16+ by program start (must also be a current junior or senior)",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or permanent resident living in the U.S. and attending high school in the U.S.",
        "income_requirement": "Need-based stipends considered if family AGI is under $80,000 or for other circumstances",
        "underrepresented_preference": "Strong preference for local Bay Area students (within about a 1-hour drive); commuter program with no housing",
        "school_nomination_required": "No",
        "other_restrictions": "Commuter only — no housing provided.",
        "stipend_status": "Limited / not guaranteed",
        "stipend_amount": "",
        "stipend_display": "Needs-based stipend possible — not guaranteed",
        "paid_status": "Limited need-based stipends; official 2026 materials say most students will not receive a stipend",
        **_not_reported(),
        "acceptance_rate_source": "Stanford SIMR does not publish an official acceptance rate.",
        "requirements": "High school junior or senior; 16+ by program start; living and attending high school in the U.S.; U.S. citizen or permanent resident",
    },
    "UCSB Research Mentorship Program (RMP)": {
        "cost": "Tuition required",
        "cost_category": "Tuition required",
        "tuition_cost": "2026: $5,600 tuition and program fees; residential housing/meals about $7,599 extra; $75 application fee",
        "financial_aid": "Available",
        "financial_aid_status": "Limited need-based scholarships available; California residents prioritized",
        "scholarship_availability": "Limited need-based scholarships; not guaranteed",
        "eligibility_summary": "Grades 10–11 (exceptional 9th considered) • 3.80+ weighted GPA",
        "eligible_grades": "9;10;11",
        "age_requirements": "Primarily current 10th and 11th graders; exceptional 9th graders considered",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "Open to qualified students, including international applicants, per UCSB pre-college materials",
        "gpa_requirement": "Minimum 3.80 weighted academic GPA",
        "income_requirement": "Scholarships are need-based and limited",
        "school_nomination_required": "No",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Not paid / Tuition-based Program",
        **_not_reported(),
        "acceptance_rate_source": "UCSB RMP does not publish an official acceptance rate.",
        "requirements": "High school student in grade 10 or 11; outstanding 9th graders may be considered; minimum 3.80 weighted academic GPA; full program commitment",
    },
    "Princeton Laboratory Learning Program (LLP)": {
        **_free_funded(),
        "eligibility_summary": "Local New Jersey high school students • Commuter only",
        "eligible_grades": "10;11;12",
        "age_requirements": "Project-specific age requirements apply",
        "nyc_residency_required": "No — local New Jersey students",
        "nyc_school_required": "No",
        "school_nomination_required": "No",
        "other_restrictions": "No housing or transportation provided; commuter research experience",
        "stipend_status": "Not paid",
        "stipend_display": "Not paid",
        "paid_status": "Unpaid / Free Research Experience",
        **_not_reported(),
        "acceptance_rate_source": "Princeton LLP does not publish an official acceptance rate.",
        "requirements": "Local New Jersey high school student; no housing or transportation provided; project-specific requirements apply",
    },
    "Brookhaven National Laboratory High School Research Program (HSRP)": {
        **_free_funded(),
        "eligibility_summary": "Typically after 11th grade • Age 16+ • U.S. citizen or permanent resident",
        "eligible_grades": "11;12",
        "age_requirements": "16+ by program start",
        "nyc_residency_required": "No",
        "nyc_school_required": "No",
        "citizenship_requirement": "U.S. citizen or lawful permanent resident",
        "school_nomination_required": "No — two recommendations required",
        "other_restrictions": "Commuter program; housing and transportation are not provided. Active health insurance required.",
        "stipend_status": "Unknown",
        "stipend_display": "Not publicly stated on the official HSRP page — check official site",
        "paid_status": "Check official 2027 cycle details",
        **_not_reported(),
        "acceptance_rate_source": "Brookhaven National Laboratory does not publish an official HSRP acceptance rate.",
        "requirements": "Recommended after completion of 11th grade; age 16+; U.S. citizen or permanent resident; health insurance; two recommendations; able to commute daily",
    },
    "Cold Spring Harbor Laboratory Partners for the Future": {
        **_free_funded(),
        "eligibility_summary": "Long Island students entering senior year • School nomination required",
        "eligible_grades": "11;12",
        "age_requirements": "Students entering senior year",
        "nyc_residency_required": "No — Long Island high school students",
        "nyc_school_required": "No",
        "school_nomination_required": "Yes — school science chair may nominate up to two students",
        "stipend_status": "Unknown",
        "stipend_display": "Not publicly stated — check official site",
        "paid_status": "Check official current-cycle details",
        **_not_reported(),
        "acceptance_rate_source": "CSHL does not publish an official acceptance rate. Each participating school science chair may nominate up to two students.",
        "requirements": "Long Island high school student entering senior year; must be nominated by school science chairperson",
    },
}


def apply_opportunity_transparency(records):
    """Merge source-confidence fields onto each opportunity dict."""

    for record in records:
        name = str(record.get("name", "")).strip()
        merged = dict(TRANSPARENCY_DEFAULTS)
        merged.update(TRANSPARENCY_UPDATES.get(name, {}))
        record.update(merged)

    return records
